[toolchain]

[features]
resolution = true
skip-lint = false

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[programs.localnet]
helloworld = "8weB5xqS5jbQzxmHEr2e79UUSYur6QpFwkMtdGezgtPy"