[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
helloworld = "8weB5xqS5jbQzxmHEr2e79UUSYur6QpFwkMtdGezgtPy"
# helloworld = "4tY8XxbzkpEc4tR4kE8joxtzxSj3XL9zybEWLX5b3YKL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/dev/workspace/solana-indexer/programs/local/RMyeke3NSiCHJJ6Vsaq9vJMXcpi43eTESgLfDygTgSp.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
